### ISSUE TITLE
noFork message showing for a sec between after clicking

### ISSUE THREAD

**Issue by arimbr** [arimbr/fork-stats#5]
Steps to reproduce:
1. Search for angular/angular
2. Go to last page (page 10)
3. Click radio button 100 to show 100 forks per page

Result: "Sorry, nobody gave a fork!" alert appears for a second before new page loads

**Comment by whoami1201** [comment]
I noticed that too.. The problem is here:
![network](https://cloud.githubusercontent.com/assets/2924782/6289550/9b124648-b929-11e4-82e4-de542932ce19.JPG)

The page captured the "display per page" button first -- only then it noticed the page has also changed, hence the 2 requests. The reason behind is that the current page when event "display per page" fired was larger than the total number of pages.

I have added a helper function that checks the current page and resets it to 1 if it's larger than the total number of pages.
![image](https://cloud.githubusercontent.com/assets/2924782/6289993/90f8efce-b92c-11e4-8983-6edddb2b37e6.png)
